### ISSUE TITLE
Does this ARG VERSION work?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bioconductor_devel#6]
https://github.com/waldronlab/bioconductor_devel/blob/158fd22b759b9775554d211f142dcc5cd181508f/Dockerfile#L3

There haven't been successful builds on dockerhub for a while (e.g. https://hub.docker.com/r/waldronlab/bioconductor_devel) and I'm wondering if this is why. One workaround would be inelegantly creating `devel/` and `release/` directories with their own Dockerfiles. I could do this, but want to discuss with you @LiNk-NY first since you've done all this work...

**Comment by LiNk-NY** [comment]
Hi Levi, 

I don't think I have access to the `waldronlab` account on Docker Hub. 
Usually, one would create a webhook to the GitHub repository so that any
changes to the repository would cause the image to be built on Docker Hub. 

I modified this Dockerfile to be used in conjunction with the `bioconductor` script. 

I was rebuilding the image so that users are mapped to the same user ID. 

This is no longer necessary as we are using _dedicated_ package folders
for the container image. Previously, I thought that we could use our existing
local package directories with the Docker image but this was not the intended
use case. 

I guess the question would be what do we want to do in addition to what 
`bioconductor_full` already provides? 
The answer to that would go into the current `Dockerfile`. We could include
additional tools that are already listed in the Dockerfile.

**Comment by lwaldron** [comment]
The most important thing I want in addition to what `bioconductor_full` provides is to add LaTex so that `R CMD check` will work, see https://github.com/Bioconductor/bioconductor_full/issues/10, as is already in this Dockerfile.

A secondary thing I plan to add is a Jupyter notebook installation.

As for "This is no longer necessary as we are using dedicated package folders
for the container image" - I don't *think* this is necessary either for using a shared local package directory. Mounted volumes e.g. on wallabe4 will have host permissions, which can be managed in the usual way with group permissions that we use without Docker.

**Comment by lwaldron** [comment]
BTW Dockerhub is already attempting to build the image (e.g. https://hub.docker.com/repository/registry-1.docker.io/waldronlab/bioconductor_devel/builds/bef69c82-dbe0-4ab4-a892-2262d2a4e684) but it fails with errors like:
```
Starting build of index.docker.io/waldronlab/bioconductor_devel:latest...
Step 1/7 : ARG VERSION
Step 2/7 : FROM bioconductor/bioconductor_full:${VERSION}
invalid reference format
```

**Comment by LiNk-NY** [comment]
> The most important thing I want in addition to what `bioconductor_full` provides is to add LaTex so that `R CMD check` will work, see [Bioconductor/bioconductor_full#10](https://github.com/Bioconductor/bioconductor_full/issues/10), as is already in this Dockerfile.
> 
> A secondary thing I plan to add is a Jupyter notebook installation.
> 
> As for "This is no longer necessary as we are using dedicated package folders
> for the container image" - I don't _think_ this is necessary either for using a shared local package directory. Mounted volumes e.g. on wallabe4 will have host permissions, which can be managed in the usual way with group permissions that we use without Docker.

We cannot share local package directories with containers because some packages have shared libraries. 

AFAICT, loading packages with dynamic libraries (such as `stringi`) that were installed locally is not possible because the links to shared libraries break. That is why it is recommended to have a _separate set_ of installed packages dedicated to the container. 

```
docker run -ti --user rstudio -v $HOME:/home/rstudio -v $HOME/R/bioc-devel:/usr/local/lib/R/host-site-library -w /home/rstudio bioconductor/bioconductor_full:devel R
```

```r
> library(stringi)
Error: package or namespace load failed for 'stringi' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/host-site-library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
```
@lwaldron
